DISTANCE_UNIT_KM = 'km'
DISTANCE_UNIT_MILES = 'mi'

EARTH_RADIUS_KM = 6371
EARTH_RADIUS_MILES = 3959

EARTH_RADIUS_CHOICES = (
    (DISTANCE_UNIT_KM, EARTH_RADIUS_KM),
    (DISTANCE_UNIT_MILES, EARTH_RADIUS_MILES)
)
